
###
POST  http://localhost:7000/service-user/address-type/ HTTP/1.1
content-type: application/json

{
    "description":"trabalho"
}


###
GET  http://localhost:7000/service-user/address-type/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJ1c2VyIiwiaWRVc2VyIjoxLCJpYXQiOjE3MjU0MDUwODUsImV4cCI6MTcyNTQwODY4NX0.ageJuID6sVfDanMkRgSswwXgGdsESLRcH7IjdY1jc44

###
GET  http://localhost:7000/service-user/address-type/2 HTTP/1.1

###
PATCH  http://localhost:7000/service-user/address-type/2 HTTP/1.1
content-type: application/json

{
    "description": "trabalho alterado"
    
}

###
DELETE  http://localhost:7000/service-user/address-type/2 HTTP/1.1
