
###
POST  http://localhost:7000/service-user/group/ HTTP/1.1
content-type: application/json

{
    "name": "administrativo"
    
}

###
GET  http://localhost:7000/service-user/group/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6MSwiaWF0IjoxNzEyNzA2NTMxLCJleHAiOjE3MTI3MTAxMzF9.M3GH5bwxACeXxZxa95JqT-gF_LgJHhN9OIam0d4HhQg

###
GET  http://localhost:7000/service-user/group/6 HTTP/1.1

###
PATCH  http://localhost:7000/service-user/group/6 HTTP/1.1
content-type: application/json

{
    "name": "administrativo alt"
    
}

###
DELETE  http://localhost:7000/service-user/group/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6MSwiaWF0IjoxNzEyNzA2NTMxLCJleHAiOjE3MTI3MTAxMzF9.M3GH5bwxACeXxZxa95JqT-gF_LgJHhN9OIam0d4HhQg
