###
POST  http://localhost:7000/service-user/rule/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6MSwiaWF0IjoxNzEyNzA2NTMxLCJleHAiOjE3MTI3MTAxMzF9.M3GH5bwxACeXxZxa95JqT-gF_LgJHhN9OIam0d4HhQg
content-type: application/json

{
    "description":"Alterar Produtos"
}

###
GET  http://localhost:7000/service-user/rule/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6MSwiaWF0IjoxNzEzNDg1NzM0LCJleHAiOjE3MTM0ODkzMzR9.dniHflUus43XLSRaMsewb8Z1UA1L-Dcm5qFAfqaJIRk

###
GET  http://localhost:7000/service-user/rule/2 HTTP/1.1

###
PATCH  http://localhost:7000/service-user/rule/4 HTTP/1.1
content-type: application/json

{
    "description": "alterar"
    
}

###
DELETE  http://localhost:7000/service-user/rule/2 HTTP/1.1
