
###
POST  http://localhost:7000/service-user/staff/ HTTP/1.1
content-type: application/json

{
    "name": "Breno",
    "login": " breno",
    "password": "123456",
    "active": true,
    "sector": "Amoxarifado",
    "role": "Ferreiro",
    "id_number": "112233445",
    "cpf": " 31254478934"
}

###
GET  http://localhost:7000/service-user/staff/ HTTP/1.1

###
GET  http://localhost:7000/service-user/staff/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6NCwiaWF0IjoxNzE0NjkzODM5LCJleHAiOjE3MTQ2OTc0Mzl9.yJbV_pgtuFxk4oxX09pTd9uC9MEdB73QRlGNarXPYCA

###
PATCH  http://localhost:7000/service-user/staff/8 HTTP/1.1
content-type: application/json

{
   "sector": "Compras"
    
}

###
DELETE  http://localhost:7000/service-user/staff/4 HTTP/1.1



###
POST  http://localhost:7000/service-user/staff/signin/ HTTP/1.1
content-type: application/json

{
    "login": "murilo",
    "password": "123456"

}

###
POST  http://localhost:7000/service-user/staff/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6NCwiaWF0IjoxNzE0NjkzNDA2LCJleHAiOjE3MTQ3MDQyMDZ9.g7PEt2pBbcknIGU0VoGFYdYY9gnAF5D-_75d8tBwMr0
content-type: application/json

{"items":10,"page":1,"order":{"name":"ASC"}}


###
GET  http://localhost:7000/service-user/staff/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJzdGFmZiIsImlkVXNlciI6NCwiaWF0IjoxNzE0NjkzNTMzLCJleHAiOjE3MTQ3MDQzMzN9.Umqfz6hZXddWwPCpwUBduBoA6WQnFggVJnNDkWJLwYY
me